- hosts: localhost
 
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: ansible
      location: eastus

  - name: Create a public ip address
    azure_rm_publicipaddress:
      resource_group: ansible
      name: public_ip
      allocation_method: static